version: '3.8'

services:
  aitrainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aitrainer
    ports:
      - "5000:5000"
    volumes:
      - ./lib:/app/lib
      - ./output:/app/output
      - ./inputs.txt:/app/inputs.txt
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    restart: unless-stopped
